import type { Trader } from "./types/trader";
import type { Item } from "./types/item";
import type { Quest } from "./types/quest";

export const TRADERS: Trader[] = [
  {
    id: "prapor",
    name: "Prapor",
    level: 1,
    maxLevel: 4,
    reputation: 0.35,
    reputationRequiredForNextLevel: 0.6,
    kappaRequired: true,
  },
  {
    id: "therapist",
    name: "Therapist",
    level: 1,
    maxLevel: 4,
    reputation: 0.6,
    reputationRequiredForNextLevel: 0.6,
    kappaRequired: true,
  },
  {
    id: "skier",
    name: "Skier",
    level: 1,
    maxLevel: 4,
    reputation: 0.4,
    reputationRequiredForNextLevel: 0.6,
    kappaRequired: true,
  },
  {
    id: "peacekeeper",
    name: "Peacekeeper",
    level: 1,
    maxLevel: 4,
    reputation: 0.35,
    reputationRequiredForNextLevel: 0.6,
    kappaRequired: true,
  },
  {
    id: "mechanic",
    name: "Mechanic",
    level: 1,
    maxLevel: 4,
    reputation: 0.6,
    reputationRequiredForNextLevel: 0.6,
    kappaRequired: true,
  },
  {
    id: "ragman",
    name: "Ragman",
    level: 1,
    maxLevel: 4,
    reputation: 0.4,
    reputationRequiredForNextLevel: 0.6,
    kappaRequired: true,
  },
  {
    id: "jaeger",
    name: "Jaeger",
    level: 1,
    maxLevel: 4,
    reputation: 0.25,
    reputationRequiredForNextLevel: 0.6,
    kappaRequired: true,
  },
  {
    id: "fence",
    name: "Fence",
    level: 1,
    maxLevel: 2,
    reputation: 0.2,
    reputationRequiredForNextLevel: 0.6,
    kappaRequired: true,
  },
  {
    id: "ref",
    name: "Ref",
    level: 1,
    maxLevel: 4,
    reputation: 0.1,
    reputationRequiredForNextLevel: 0.6,
    kappaRequired: false,
  },
];

export const ITEMS: Item[] = [
  {
    id: "ledx",
    name: "LEDX Skin Transilluminator",
    category: "Medical",
    rarity: "legendary",
    neededForKappa: true,
    quantityRequired: 3,
    quantityOwned: 1,
    foundInRaid: true,
  },
  {
    id: "gpu",
    name: "Graphics card",
    category: "Electronics",
    rarity: "epic",
    neededForKappa: true,
    quantityRequired: 10,
    quantityOwned: 7,
    foundInRaid: true,
  },
  {
    id: "lion",
    name: "Bronze lion",
    category: "Valuables",
    rarity: "epic",
    neededForKappa: true,
    quantityRequired: 5,
    quantityOwned: 2,
    foundInRaid: false,
  },
  {
    id: "flash-drive",
    name: "Flash drive",
    category: "Electronics",
    rarity: "rare",
    neededForKappa: false,
    quantityRequired: 4,
    quantityOwned: 4,
    foundInRaid: true,
  },
  {
    id: "batteries",
    name: "Car battery",
    category: "Barter",
    rarity: "rare",
    neededForKappa: false,
    quantityRequired: 4,
    quantityOwned: 1,
    foundInRaid: false,
  },
];

// Placeholder QUESTS export so dashboard and other components can import it.
// This will be replaced by live quest data from the tarkov.dev API.
export const QUESTS: Quest[] = [];
